import { AnimeFormat } from "@/types";

export const dummyAnimes: AnimeFormat[] = [
  {
    id: 58524,
    title: 'Himesama "Goumon" no Jikan desu 2nd Season',
    image: "https://cdn.myanimelist.net/images/anime/1025/142279.webp",
    genres: ["Comedy", "Fantasy", "Gourmet"],
  },
  {
    id: 58524,
    title: 'Himesama "Goumon" no Jikan desu 2nd Season',
    image: "https://cdn.myanimelist.net/images/anime/1025/142279.webp",
    genres: ["Comedy", "Fantasy", "Gourmet"],
  },
  {
    id: 58531,
    title: "High Card: The Flowers Bloom",
    image: "https://cdn.myanimelist.net/images/anime/1751/142289.webp",
    genres: [],
  },
  {
    id: 16498,
    title: "Shingeki no Kyojin",
    image: "https://cdn.myanimelist.net/images/anime/10/47347.webp",
    genres: ["Action", "Award Winning", "Drama", "Suspense"],
  },
  {
    id: 1535,
    title: "Death Note",
    image: "https://cdn.myanimelist.net/images/anime/1079/138100.webp",
    genres: ["Supernatural", "Suspense"],
  },
  {
    id: 5114,
    title: "Fullmetal Alchemist: Brotherhood",
    image: "https://cdn.myanimelist.net/images/anime/1208/94745.webp",
    genres: ["Action", "Adventure", "Drama", "Fantasy"],
  },
  {
    id: 30276,
    title: "One Punch Man",
    image: "https://cdn.myanimelist.net/images/anime/12/76049.webp",
    genres: ["Action", "Comedy"],
  },
  {
    id: 11757,
    title: "Sword Art Online",
    image: "https://cdn.myanimelist.net/images/anime/11/39717.webp",
    genres: ["Action", "Adventure", "Fantasy", "Romance"],
  },
  {
    id: 31964,
    title: "Boku no Hero Academia",
    image: "https://cdn.myanimelist.net/images/anime/10/78745.webp",
    genres: ["Action"],
  },
  {
    id: 38000,
    title: "Kimetsu no Yaiba",
    image: "https://cdn.myanimelist.net/images/anime/1286/99889.webp",
    genres: ["Action", "Award Winning", "Fantasy"],
  },
  {
    id: 20,
    title: "Naruto",
    image: "https://cdn.myanimelist.net/images/anime/13/17405.webp",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 11061,
    title: "Hunter x Hunter (2011)",
    image: "https://cdn.myanimelist.net/images/anime/1337/99013.webp",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 22319,
    title: "Tokyo Ghoul",
    image: "https://cdn.myanimelist.net/images/anime/1498/134443.webp",
    genres: ["Action", "Fantasy", "Horror", "Suspense"],
  },
  {
    id: 32281,
    title: "Kimi no Na wa.",
    image: "https://cdn.myanimelist.net/images/anime/5/87048.webp",
    genres: ["Award Winning", "Drama", "Supernatural"],
  },
  {
    id: 25777,
    title: "Shingeki no Kyojin Season 2",
    image: "https://cdn.myanimelist.net/images/anime/4/84177.webp",
    genres: ["Action", "Drama", "Suspense"],
  },
  {
    id: 9253,
    title: "Steins;Gate",
    image: "https://cdn.myanimelist.net/images/anime/1935/127974.webp",
    genres: ["Drama", "Sci-Fi", "Suspense"],
  },
  {
    id: 40748,
    title: "Jujutsu Kaisen",
    image: "https://cdn.myanimelist.net/images/anime/1171/109222.webp",
    genres: ["Action", "Award Winning", "Fantasy"],
  },
  {
    id: 33486,
    title: "Boku no Hero Academia 2nd Season",
    image: "https://cdn.myanimelist.net/images/anime/12/85221.webp",
    genres: ["Action"],
  },
  {
    id: 1735,
    title: "Naruto: Shippuuden",
    image: "https://cdn.myanimelist.net/images/anime/1565/111305.webp",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 19815,
    title: "No Game No Life",
    image: "https://cdn.myanimelist.net/images/anime/1074/111944.webp",
    genres: ["Comedy", "Fantasy", "Ecchi"],
  },
  {
    id: 35760,
    title: "Shingeki no Kyojin Season 3",
    image: "https://cdn.myanimelist.net/images/anime/1173/92110.webp",
    genres: ["Action", "Drama", "Suspense"],
  },
  {
    id: 21,
    title: "One Piece",
    image: "https://cdn.myanimelist.net/images/anime/1244/138851.webp",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 28851,
    title: "Koe no Katachi",
    image: "https://cdn.myanimelist.net/images/anime/1122/96435.webp",
    genres: ["Award Winning", "Drama"],
  },
  {
    id: 38524,
    title: "Shingeki no Kyojin Season 3 Part 2",
    image: "https://cdn.myanimelist.net/images/anime/1517/100633.webp",
    genres: ["Action", "Drama", "Suspense"],
  },
  {
    id: 1575,
    title: "Code Geass: Hangyaku no Lelouch",
    image: "https://cdn.myanimelist.net/images/anime/1032/135088.webp",
    genres: ["Action", "Award Winning", "Drama", "Sci-Fi"],
  },
  {
    id: 23273,
    title: "Shigatsu wa Kimi no Uso",
    image: "https://cdn.myanimelist.net/images/anime/3/67177.webp",
    genres: ["Drama", "Romance"],
  },
  {
    id: 4224,
    title: "Toradora!",
    image: "https://cdn.myanimelist.net/images/anime/13/22128.webp",
    genres: ["Drama", "Romance"],
  },
  {
    id: 31240,
    title: "Re:Zero kara Hajimeru Isekai Seikatsu",
    image: "https://cdn.myanimelist.net/images/anime/1522/128039.webp",
    genres: ["Drama", "Fantasy", "Suspense"],
  },
  {
    id: 36456,
    title: "Boku no Hero Academia 3rd Season",
    image: "https://cdn.myanimelist.net/images/anime/1319/92084.webp",
    genres: ["Action"],
  },
  {
    id: 20507,
    title: "Noragami",
    image: "https://cdn.myanimelist.net/images/anime/1886/128266.webp",
    genres: ["Action", "Fantasy"],
  },
  {
    id: 31043,
    title: "Boku dake ga Inai Machi",
    image: "https://cdn.myanimelist.net/images/anime/10/77957.webp",
    genres: ["Mystery", "Supernatural", "Suspense"],
  },
  {
    id: 22199,
    title: "Akame ga Kill!",
    image: "https://cdn.myanimelist.net/images/anime/1429/95946.webp",
    genres: ["Action", "Fantasy"],
  },
  {
    id: 6547,
    title: "Angel Beats!",
    image: "https://cdn.myanimelist.net/images/anime/1244/111115.webp",
    genres: ["Drama", "Supernatural"],
  },
  {
    id: 32182,
    title: "Mob Psycho 100",
    image: "https://cdn.myanimelist.net/images/anime/8/80356.webp",
    genres: ["Action", "Comedy", "Supernatural"],
  },
  {
    id: 23755,
    title: "Nanatsu no Taizai",
    image: "https://cdn.myanimelist.net/images/anime/8/65409.webp",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 24833,
    title: "Ansatsu Kyoushitsu",
    image: "https://cdn.myanimelist.net/images/anime/5/75639.webp",
    genres: ["Action", "Comedy"],
  },
  {
    id: 10620,
    title: "Mirai Nikki (TV)",
    image: "https://cdn.myanimelist.net/images/anime/13/33465.webp",
    genres: ["Action", "Supernatural", "Suspense"],
  },
  {
    id: 40028,
    title: "Shingeki no Kyojin: The Final Season",
    image: "https://cdn.myanimelist.net/images/anime/1000/110531.webp",
    genres: ["Action", "Drama", "Suspense"],
  },
  {
    id: 21881,
    title: "Sword Art Online II",
    image: "https://cdn.myanimelist.net/images/anime/1223/121999.webp",
    genres: ["Action", "Adventure", "Fantasy", "Romance"],
  },
  {
    id: 20583,
    title: "Haikyuu!!",
    image: "https://cdn.myanimelist.net/images/anime/7/76014.webp",
    genres: ["Sports"],
  },
  {
    id: 37779,
    title: "Yakusoku no Neverland",
    image: "https://cdn.myanimelist.net/images/anime/1830/118780.webp",
    genres: ["Fantasy", "Mystery", "Sci-Fi", "Suspense"],
  },
  {
    id: 269,
    title: "Bleach",
    image: "https://cdn.myanimelist.net/images/anime/3/40451.webp",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 30831,
    title: "Kono Subarashii Sekai ni Shukufuku wo!",
    image: "https://cdn.myanimelist.net/images/anime/8/77831.webp",
    genres: ["Adventure", "Comedy", "Fantasy"],
  },
  {
    id: 9919,
    title: "Ao no Exorcist",
    image: "https://cdn.myanimelist.net/images/anime/10/75195.webp",
    genres: ["Action", "Fantasy"],
  },
  {
    id: 22535,
    title: "Kiseijuu: Sei no Kakuritsu",
    image: "https://cdn.myanimelist.net/images/anime/3/73178.webp",
    genres: ["Action", "Horror", "Sci-Fi", "Suspense"],
  },
  {
    id: 1,
    title: "Cowboy Bebop",
    image: "https://cdn.myanimelist.net/images/anime/4/19644.webp",
    genres: ["Action", "Award Winning", "Sci-Fi"],
  },
  {
    id: 199,
    title: "Sen to Chihiro no Kamikakushi",
    image: "https://cdn.myanimelist.net/images/anime/6/79597.webp",
    genres: ["Adventure", "Award Winning", "Supernatural"],
  },
  {
    id: 30,
    title: "Shinseiki Evangelion",
    image: "https://cdn.myanimelist.net/images/anime/1314/108941.webp",
    genres: ["Action", "Avant Garde", "Award Winning", "Drama", "Sci-Fi", "Suspense"],
  },
  {
    id: 2904,
    title: "Code Geass: Hangyaku no Lelouch R2",
    image: "https://cdn.myanimelist.net/images/anime/1088/135089.webp",
    genres: ["Action", "Award Winning", "Drama", "Sci-Fi"],
  },
  {
    id: 33352,
    title: "Violet Evergarden",
    image: "https://cdn.myanimelist.net/images/anime/1795/95088.webp",
    genres: ["Drama", "Fantasy"],
  },
  {
    id: 27899,
    title: "Tokyo Ghoul √A",
    image: "https://cdn.myanimelist.net/images/anime/1889/123307.webp",
    genres: ["Action", "Fantasy", "Horror", "Suspense"],
  },
  {
    id: 28223,
    title: "Death Parade",
    image: "https://cdn.myanimelist.net/images/anime/5/71553.webp",
    genres: ["Drama", "Supernatural", "Suspense"],
  },
  {
    id: 6702,
    title: "Fairy Tail",
    image: "https://cdn.myanimelist.net/images/anime/5/18179.webp",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 38691,
    title: "Dr. Stone",
    image: "https://cdn.myanimelist.net/images/anime/1613/102576.webp",
    genres: ["Adventure", "Comedy", "Sci-Fi"],
  },
  {
    id: 37999,
    title: "Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen",
    image: "https://cdn.myanimelist.net/images/anime/1295/106551.webp",
    genres: ["Comedy"],
  },
  {
    id: 37450,
    title: "Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai",
    image: "https://cdn.myanimelist.net/images/anime/1301/93586.webp",
    genres: ["Drama", "Romance", "Supernatural"],
  },
  {
    id: 18679,
    title: "Kill la Kill",
    image: "https://cdn.myanimelist.net/images/anime/1464/111943.webp",
    genres: ["Action", "Comedy", "Fantasy", "Ecchi"],
  },
  {
    id: 38408,
    title: "Boku no Hero Academia 4th Season",
    image: "https://cdn.myanimelist.net/images/anime/1412/107914.webp",
    genres: ["Action"],
  },
  {
    id: 34134,
    title: "One Punch Man 2nd Season",
    image: "https://cdn.myanimelist.net/images/anime/1247/122044.webp",
    genres: ["Action", "Comedy"],
  },
  {
    id: 11111,
    title: "Another",
    image: "https://cdn.myanimelist.net/images/anime/4/75509.webp",
    genres: ["Horror", "Mystery", "Supernatural"],
  },
  {
    id: 14719,
    title: "JoJo no Kimyou na Bouken (TV)",
    image: "https://cdn.myanimelist.net/images/anime/3/40409.webp",
    genres: ["Action", "Adventure", "Supernatural"],
  },
  {
    id: 34572,
    title: "Black Clover",
    image: "https://cdn.myanimelist.net/images/anime/2/88336.webp",
    genres: ["Action", "Comedy", "Fantasy"],
  },
  {
    id: 35849,
    title: "Darling in the FranXX",
    image: "https://cdn.myanimelist.net/images/anime/1614/90408.webp",
    genres: ["Action", "Drama", "Romance", "Sci-Fi"],
  },
  {
    id: 28171,
    title: "Shokugeki no Souma",
    image: "https://cdn.myanimelist.net/images/anime/3/72943.webp",
    genres: ["Gourmet", "Ecchi"],
  },
  {
    id: 13601,
    title: "Psycho-Pass",
    image: "https://cdn.myanimelist.net/images/anime/1314/142015.webp",
    genres: ["Action", "Mystery", "Sci-Fi", "Suspense"],
  },
  {
    id: 3588,
    title: "Soul Eater",
    image: "https://cdn.myanimelist.net/images/anime/9/7804.webp",
    genres: ["Action", "Comedy", "Fantasy"],
  },
  {
    id: 2001,
    title: "Tengen Toppa Gurren Lagann",
    image: "https://cdn.myanimelist.net/images/anime/4/5123.webp",
    genres: ["Action", "Adventure", "Award Winning", "Sci-Fi"],
  },
  {
    id: 28999,
    title: "Charlotte",
    image: "https://cdn.myanimelist.net/images/anime/12/74683.webp",
    genres: ["Drama"],
  },
  {
    id: 9989,
    title: "Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.",
    image: "https://cdn.myanimelist.net/images/anime/5/79697.webp",
    genres: ["Drama", "Supernatural"],
  },
  {
    id: 29803,
    title: "Overlord",
    image: "https://cdn.myanimelist.net/images/anime/7/88019.webp",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 35790,
    title: "Tate no Yuusha no Nariagari",
    image: "https://cdn.myanimelist.net/images/anime/1490/101365.webp",
    genres: ["Action", "Adventure", "Drama", "Fantasy"],
  },
  {
    id: 15809,
    title: "Hataraku Maou-sama!",
    image: "https://cdn.myanimelist.net/images/anime/3/50177.webp",
    genres: ["Comedy", "Fantasy"],
  },
  {
    id: 50265,
    title: "Spy x Family",
    image: "https://cdn.myanimelist.net/images/anime/1441/122795.webp",
    genres: ["Action", "Award Winning", "Comedy"],
  },
  {
    id: 40456,
    title: "Kimetsu no Yaiba Movie: Mugen Ressha-hen",
    image: "https://cdn.myanimelist.net/images/anime/1704/106947.webp",
    genres: ["Action", "Fantasy"],
  },
  {
    id: 28121,
    title: "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka",
    image: "https://cdn.myanimelist.net/images/anime/2/70187.webp",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 37510,
    title: "Mob Psycho 100 II",
    image: "https://cdn.myanimelist.net/images/anime/1918/96303.webp",
    genres: ["Action", "Comedy", "Supernatural"],
  },
  {
    id: 226,
    title: "Elfen Lied",
    image: "https://cdn.myanimelist.net/images/anime/1780/121555.webp",
    genres: ["Action", "Drama", "Horror", "Romance", "Supernatural", "Suspense"],
  },
  {
    id: 8074,
    title: "Highschool of the Dead",
    image: "https://cdn.myanimelist.net/images/anime/11/78311.webp",
    genres: ["Action", "Horror", "Supernatural", "Suspense", "Ecchi"],
  },
  {
    id: 32937,
    title: "Kono Subarashii Sekai ni Shukufuku wo! 2",
    image: "https://cdn.myanimelist.net/images/anime/2/83188.webp",
    genres: ["Adventure", "Comedy", "Fantasy"],
  },
  {
    id: 37521,
    title: "Vinland Saga",
    image: "https://cdn.myanimelist.net/images/anime/1500/103005.webp",
    genres: ["Action", "Adventure", "Drama"],
  },
  {
    id: 10087,
    title: "Fate/Zero",
    image: "https://cdn.myanimelist.net/images/anime/1887/117644.webp",
    genres: ["Action", "Fantasy", "Supernatural"],
  },
  {
    id: 44511,
    title: "Chainsaw Man",
    image: "https://cdn.myanimelist.net/images/anime/1806/126216.webp",
    genres: ["Action", "Fantasy"],
  },
  {
    id: 34933,
    title: "Kakegurui",
    image: "https://cdn.myanimelist.net/images/anime/3/86578.webp",
    genres: ["Drama", "Mystery", "Suspense"],
  },
  {
    id: 121,
    title: "Fullmetal Alchemist",
    image: "https://cdn.myanimelist.net/images/anime/10/75815.webp",
    genres: ["Action", "Adventure", "Award Winning", "Drama", "Fantasy"],
  },
  {
    id: 30503,
    title: "Noragami Aragoto",
    image: "https://cdn.myanimelist.net/images/anime/1689/94850.webp",
    genres: ["Action", "Fantasy"],
  },
  {
    id: 14813,
    title: "Yahari Ore no Seishun Love Comedy wa Machigatteiru.",
    image: "https://cdn.myanimelist.net/images/anime/1786/120117.webp",
    genres: ["Comedy", "Romance"],
  },
  {
    id: 37430,
    title: "Tensei shitara Slime Datta Ken",
    image: "https://cdn.myanimelist.net/images/anime/1069/123309.webp",
    genres: ["Action", "Adventure", "Comedy", "Fantasy"],
  },
  {
    id: 30654,
    title: "Ansatsu Kyoushitsu 2nd Season",
    image: "https://cdn.myanimelist.net/images/anime/8/77966.webp",
    genres: ["Action", "Comedy"],
  },
  {
    id: 11617,
    title: "High School DxD",
    image: "https://cdn.myanimelist.net/images/anime/1331/111940.webp",
    genres: ["Action", "Comedy", "Fantasy", "Romance", "Ecchi"],
  },
  {
    id: 28891,
    title: "Haikyuu!! Second Season",
    image: "https://cdn.myanimelist.net/images/anime/9/76662.webp",
    genres: ["Sports"],
  },
  {
    id: 2167,
    title: "Clannad",
    image: "https://cdn.myanimelist.net/images/anime/1804/95033.webp",
    genres: ["Drama", "Romance", "Supernatural"],
  },
  {
    id: 47778,
    title: "Kimetsu no Yaiba: Yuukaku-hen",
    image: "https://cdn.myanimelist.net/images/anime/1908/120036.webp",
    genres: ["Action", "Fantasy"],
  },
  {
    id: 6746,
    title: "Durarara!!",
    image: "https://cdn.myanimelist.net/images/anime/10/71772.webp",
    genres: ["Action", "Mystery", "Supernatural"],
  },
  {
    id: 5081,
    title: "Bakemonogatari",
    image: "https://cdn.myanimelist.net/images/anime/11/75274.webp",
    genres: ["Mystery", "Romance", "Supernatural"],
  },
  {
    id: 31478,
    title: "Bungou Stray Dogs",
    image: "https://cdn.myanimelist.net/images/anime/3/79409.webp",
    genres: ["Action", "Mystery", "Supernatural"],
  },
  {
    id: 34599,
    title: "Made in Abyss",
    image: "https://cdn.myanimelist.net/images/anime/6/86733.webp",
    genres: ["Adventure", "Drama", "Fantasy", "Mystery", "Sci-Fi"],
  },
  {
    id: 12189,
    title: "Hyouka",
    image: "https://cdn.myanimelist.net/images/anime/13/50521.webp",
    genres: ["Mystery", "Slice of Life"],
  },
  {
    id: 42897,
    title: "Horimiya",
    image: "https://cdn.myanimelist.net/images/anime/1695/111486.webp",
    genres: ["Romance"],
  },
  {
    id: 14741,
    title: "Chuunibyou demo Koi ga Shitai!",
    image: "https://cdn.myanimelist.net/images/anime/12/46931.webp",
    genres: ["Comedy", "Romance"],
  },
  {
    id: 40591,
    title: "Kaguya-sama wa Kokurasetai? Tensai-tachi no Renai Zunousen",
    image: "https://cdn.myanimelist.net/images/anime/1764/106659.webp",
    genres: ["Comedy"],
  },
  {
    id: 26243,
    title: "Owari no Seraph",
    image: "https://cdn.myanimelist.net/images/anime/5/73474.webp",
    genres: ["Action", "Drama", "Fantasy"],
  },
  {
    id: 431,
    title: "Howl no Ugoku Shiro",
    image: "https://cdn.myanimelist.net/images/anime/1470/138723.webp",
    genres: ["Adventure", "Award Winning", "Drama", "Fantasy", "Romance"],
  },
  {
    id: 38671,
    title: "Enen no Shouboutai",
    image: "https://cdn.myanimelist.net/images/anime/1664/103275.webp",
    genres: ["Action", "Fantasy", "Sci-Fi"],
  },
  {
    id: 39535,
    title: "Mushoku Tensei: Isekai Ittara Honki Dasu",
    image: "https://cdn.myanimelist.net/images/anime/1530/117776.webp",
    genres: ["Adventure", "Drama", "Fantasy", "Ecchi"],
  },
  {
    id: 9756,
    title: "Mahou Shoujo Madoka★Magica",
    image: "https://cdn.myanimelist.net/images/anime/11/55225.webp",
    genres: ["Award Winning", "Drama", "Fantasy", "Suspense"],
  },
  {
    id: 48583,
    title: "Shingeki no Kyojin: The Final Season Part 2",
    image: "https://cdn.myanimelist.net/images/anime/1948/120625.webp",
    genres: ["Action", "Drama", "Suspense"],
  },
  {
    id: 35507,
    title: "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e",
    image: "https://cdn.myanimelist.net/images/anime/5/86830.webp",
    genres: ["Drama", "Suspense"],
  },
  {
    id: 164,
    title: "Mononoke Hime",
    image: "https://cdn.myanimelist.net/images/anime/7/75919.webp",
    genres: ["Action", "Adventure", "Award Winning", "Fantasy"],
  },
  {
    id: 7054,
    title: "Kaichou wa Maid-sama!",
    image: "https://cdn.myanimelist.net/images/anime/6/25254.webp",
    genres: ["Comedy", "Romance"],
  },
  {
    id: 13759,
    title: "Sakura-sou no Pet na Kanojo",
    image: "https://cdn.myanimelist.net/images/anime/4/43643.webp",
    genres: ["Drama", "Romance"],
  },
  {
    id: 42249,
    title: "Tokyo Revengers",
    image: "https://cdn.myanimelist.net/images/anime/1839/122012.webp",
    genres: ["Action", "Drama", "Supernatural"],
  },
  {
    id: 6880,
    title: "Deadman Wonderland",
    image: "https://cdn.myanimelist.net/images/anime/9/75299.webp",
    genres: ["Action", "Horror", "Sci-Fi", "Supernatural", "Suspense"],
  },
  {
    id: 205,
    title: "Samurai Champloo",
    image: "https://cdn.myanimelist.net/images/anime/1375/121599.webp",
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: 33206,
    title: "Kobayashi-san Chi no Maid Dragon",
    image: "https://cdn.myanimelist.net/images/anime/5/85434.webp",
    genres: ["Fantasy", "Slice of Life"],
  },
  {
    id: 813,
    title: "Dragon Ball Z",
    image: "https://cdn.myanimelist.net/images/anime/1277/142022.webp",
    genres: ["Action", "Adventure", "Comedy", "Fantasy"],
  },
  {
    id: 37520,
    title: "Dororo",
    image: "https://cdn.myanimelist.net/images/anime/1879/100467.webp",
    genres: ["Action", "Adventure", "Supernatural"],
  },
  {
    id: 10793,
    title: "Guilty Crown",
    image: "https://cdn.myanimelist.net/images/anime/1566/133912.webp",
    genres: ["Action", "Drama", "Sci-Fi"],
  },
  {
    id: 20899,
    title: "JoJo no Kimyou na Bouken Part 3: Stardust Crusaders",
    image: "https://cdn.myanimelist.net/images/anime/11/55267.webp",
    genres: ["Action", "Adventure", "Supernatural"],
  },
  {
    id: 11771,
    title: "Kuroko no Basket",
    image: "https://cdn.myanimelist.net/images/anime/11/50453.webp",
    genres: ["Sports"],
  },
  {
    id: 32935,
    title: "Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen Koukou",
    image: "https://cdn.myanimelist.net/images/anime/7/81992.webp",
    genres: ["Sports"],
  },
  {
    id: 4181,
    title: "Clannad: After Story",
    image: "https://cdn.myanimelist.net/images/anime/1299/110774.webp",
    genres: ["Drama", "Romance", "Supernatural"],
  },
  {
    id: 36511,
    title: "Tokyo Ghoul:re",
    image: "https://cdn.myanimelist.net/images/anime/1063/95086.webp",
    genres: ["Action", "Fantasy", "Horror", "Suspense"],
  },
  {
    id: 4898,
    title: "Kuroshitsuji",
    image: "https://cdn.myanimelist.net/images/anime/1467/137783.webp",
    genres: ["Action", "Fantasy", "Mystery"],
  },
  {
    id: 41587,
    title: "Boku no Hero Academia 5th Season",
    image: "https://cdn.myanimelist.net/images/anime/1911/113611.webp",
    genres: ["Action"],
  },
  {
    id: 18897,
    title: "Nisekoi",
    image: "https://cdn.myanimelist.net/images/anime/13/75587.webp",
    genres: ["Comedy", "Romance"],
  },
  {
    id: 18153,
    title: "Kyoukai no Kanata",
    image: "https://cdn.myanimelist.net/images/anime/3/85468.webp",
    genres: ["Action", "Fantasy"],
  },
  {
    id: 23283,
    title: "Zankyou no Terror",
    image: "https://cdn.myanimelist.net/images/anime/1417/117422.webp",
    genres: ["Mystery", "Suspense"],
  },
  {
    id: 35120,
    title: "Devilman: Crybaby",
    image: "https://cdn.myanimelist.net/images/anime/2/89973.webp",
    genres: ["Action", "Avant Garde", "Horror", "Supernatural"],
  },
  {
    id: 32282,
    title: "Shokugeki no Souma: Ni no Sara",
    image: "https://cdn.myanimelist.net/images/anime/8/79353.webp",
    genres: ["Gourmet", "Ecchi"],
  },
  {
    id: 34577,
    title: "Nanatsu no Taizai: Imashime no Fukkatsu",
    image: "https://cdn.myanimelist.net/images/anime/11/90089.webp",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 853,
    title: "Ouran Koukou Host Club",
    image: "https://cdn.myanimelist.net/images/anime/2/71992.webp",
    genres: ["Comedy", "Romance"],
  },
  {
    id: 37349,
    title: "Goblin Slayer",
    image: "https://cdn.myanimelist.net/images/anime/1719/95621.webp",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 31933,
    title: "JoJo no Kimyou na Bouken Part 4: Diamond wa Kudakenai",
    image: "https://cdn.myanimelist.net/images/anime/3/79156.webp",
    genres: ["Action", "Adventure", "Supernatural"],
  },
  {
    id: 17265,
    title: "Log Horizon",
    image: "https://cdn.myanimelist.net/images/anime/5/84004.webp",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 11741,
    title: "Fate/Zero 2nd Season",
    image: "https://cdn.myanimelist.net/images/anime/1522/117645.webp",
    genres: ["Action", "Fantasy", "Supernatural"],
  },
  {
    id: 26055,
    title: "JoJo no Kimyou na Bouken Part 3: Stardust Crusaders 2nd Season",
    image: "https://cdn.myanimelist.net/images/anime/11/75045.webp",
    genres: ["Action", "Adventure", "Supernatural"],
  },
  {
    id: 19,
    title: "Monster",
    image: "https://cdn.myanimelist.net/images/anime/10/18793.webp",
    genres: ["Drama", "Mystery", "Suspense"],
  },
  {
    id: 39587,
    title: "Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season",
    image: "https://cdn.myanimelist.net/images/anime/1444/108005.webp",
    genres: ["Drama", "Fantasy", "Suspense"],
  },
  {
    id: 33255,
    title: "Saiki Kusuo no Ψ-nan",
    image: "https://cdn.myanimelist.net/images/anime/11/80167.webp",
    genres: ["Comedy", "Supernatural"],
  },
  {
    id: 14227,
    title: "Tonari no Kaibutsu-kun",
    image: "https://cdn.myanimelist.net/images/anime/4/39779.webp",
    genres: ["Comedy", "Romance"],
  },
  {
    id: 22297,
    title: "Fate/stay night: Unlimited Blade Works",
    image: "https://cdn.myanimelist.net/images/anime/12/67333.webp",
    genres: ["Action", "Fantasy", "Supernatural"],
  },
  {
    id: 918,
    title: "Gintama",
    image: "https://cdn.myanimelist.net/images/anime/10/73274.webp",
    genres: ["Action", "Comedy", "Sci-Fi"],
  },
  {
    id: 523,
    title: "Tonari no Totoro",
    image: "https://cdn.myanimelist.net/images/anime/4/75923.webp",
    genres: ["Adventure", "Award Winning", "Supernatural"],
  },
  {
    id: 20785,
    title: "Mahouka Koukou no Rettousei",
    image: "https://cdn.myanimelist.net/images/anime/11/61039.webp",
    genres: ["Action", "Fantasy", "Romance", "Sci-Fi"],
  },
  {
    id: 23847,
    title: "Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku",
    image: "https://cdn.myanimelist.net/images/anime/11/75376.webp",
    genres: ["Comedy", "Romance"],
  },
  {
    id: 5680,
    title: "K-On!",
    image: "https://cdn.myanimelist.net/images/anime/10/76120.webp",
    genres: ["Comedy"],
  },
  {
    id: 48736,
    title: "Sono Bisque Doll wa Koi wo Suru",
    image: "https://cdn.myanimelist.net/images/anime/1179/119897.webp",
    genres: ["Romance"],
  },
  {
    id: 14513,
    title: "Magi: The Labyrinth of Magic",
    image: "https://cdn.myanimelist.net/images/anime/11/42773.webp",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 36474,
    title: "Sword Art Online: Alicization",
    image: "https://cdn.myanimelist.net/images/anime/1993/93837.webp",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 17895,
    title: "Golden Time",
    image: "https://cdn.myanimelist.net/images/anime/12/52091.webp",
    genres: ["Drama", "Romance"],
  },
  {
    id: 223,
    title: "Dragon Ball",
    image: "https://cdn.myanimelist.net/images/anime/1887/92364.webp",
    genres: ["Action", "Adventure", "Comedy", "Fantasy"],
  },
  {
    id: 30015,
    title: "ReLIFE",
    image: "https://cdn.myanimelist.net/images/anime/3/82149.webp",
    genres: ["Drama", "Romance"],
  },
  {
    id: 40852,
    title: "Dr. Stone: Stone Wars",
    image: "https://cdn.myanimelist.net/images/anime/1711/110614.webp",
    genres: ["Adventure", "Comedy", "Sci-Fi"],
  },
  {
    id: 15583,
    title: "Date A Live",
    image: "https://cdn.myanimelist.net/images/anime/13/44844.webp",
    genres: ["Action", "Fantasy", "Romance", "Sci-Fi"],
  },
  {
    id: 37991,
    title: "JoJo no Kimyou na Bouken Part 5: Ougon no Kaze",
    image: "https://cdn.myanimelist.net/images/anime/1572/95010.webp",
    genres: ["Action", "Adventure", "Supernatural"],
  },
  {
    id: 35073,
    title: "Overlord II",
    image: "https://cdn.myanimelist.net/images/anime/1212/113415.webp",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 30240,
    title: "Prison School",
    image: "https://cdn.myanimelist.net/images/anime/1286/112161.webp",
    genres: ["Comedy", "Ecchi"],
  },
  {
    id: 889,
    title: "Black Lagoon",
    image: "https://cdn.myanimelist.net/images/anime/1906/121592.webp",
    genres: ["Action"],
  },
  {
    id: 22043,
    title: "Fairy Tail (2014)",
    image: "https://cdn.myanimelist.net/images/anime/3/60551.webp",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 38826,
    title: "Tenki no Ko",
    image: "https://cdn.myanimelist.net/images/anime/1880/101146.webp",
    genres: ["Award Winning", "Drama", "Fantasy", "Romance"],
  },
  {
    id: 35968,
    title: "Wotaku ni Koi wa Muzukashii",
    image: "https://cdn.myanimelist.net/images/anime/1864/93518.webp",
    genres: ["Romance"],
  },
  {
    id: 40839,
    title: "Kanojo, Okarishimasu",
    image: "https://cdn.myanimelist.net/images/anime/1902/128382.webp",
    genres: ["Comedy", "Romance"],
  },
  {
    id: 35788,
    title: "Shokugeki no Souma: San no Sara",
    image: "https://cdn.myanimelist.net/images/anime/3/88434.webp",
    genres: ["Gourmet", "Ecchi"],
  },
  {
    id: 36098,
    title: "Kimi no Suizou wo Tabetai",
    image: "https://cdn.myanimelist.net/images/anime/1768/93291.webp",
    genres: ["Drama", "Romance"],
  },
  {
    id: 30296,
    title: "Rakudai Kishi no Cavalry",
    image: "https://cdn.myanimelist.net/images/anime/9/76493.webp",
    genres: ["Action", "Fantasy", "Romance", "Ecchi"],
  },
  {
    id: 2025,
    title: "Darker than Black: Kuro no Keiyakusha",
    image: "https://cdn.myanimelist.net/images/anime/5/19570.webp",
    genres: ["Action", "Mystery", "Sci-Fi"],
  },
  {
    id: 39551,
    title: "Tensei shitara Slime Datta Ken 2nd Season",
    image: "https://cdn.myanimelist.net/images/anime/1271/109841.webp",
    genres: ["Action", "Adventure", "Comedy", "Fantasy"],
  },
  {
    id: 38101,
    title: "5-toubun no Hanayome",
    image: "https://cdn.myanimelist.net/images/anime/1819/97947.webp",
    genres: ["Comedy", "Romance"],
  },
  {
    id: 6045,
    title: "Kimi ni Todoke",
    image: "https://cdn.myanimelist.net/images/anime/1502/124384.webp",
    genres: ["Drama", "Romance"],
  },
  {
    id: 356,
    title: "Fate/stay night",
    image: "https://cdn.myanimelist.net/images/anime/4/30327.webp",
    genres: ["Action", "Fantasy", "Romance", "Supernatural"],
  },
  {
    id: 1689,
    title: "Byousoku 5 Centimeter",
    image: "https://cdn.myanimelist.net/images/anime/1410/112994.webp",
    genres: ["Drama", "Romance"],
  },
  {
    id: 27775,
    title: "Plastic Memories",
    image: "https://cdn.myanimelist.net/images/anime/4/72750.webp",
    genres: ["Drama", "Romance", "Sci-Fi"],
  },
  {
    id: 16592,
    title: "Danganronpa: Kibou no Gakuen to Zetsubou no Koukousei The Animation",
    image: "https://cdn.myanimelist.net/images/anime/4/51463.webp",
    genres: ["Horror", "Mystery", "Suspense"],
  },
  {
    id: 38883,
    title: "Haikyuu!! To the Top",
    image: "https://cdn.myanimelist.net/images/anime/1813/105367.webp",
    genres: ["Sports"],
  },
  {
    id: 32,
    title: "Shinseiki Evangelion Movie: Air/Magokoro wo, Kimi ni",
    image: "https://cdn.myanimelist.net/images/anime/1404/98182.webp",
    genres: ["Action", "Avant Garde", "Drama", "Sci-Fi", "Suspense"],
  },
  {
    id: 777,
    title: "Hellsing Ultimate",
    image: "https://cdn.myanimelist.net/images/anime/6/7333.webp",
    genres: ["Action", "Horror", "Supernatural"],
  },
  {
    id: 23289,
    title: "Gekkan Shoujo Nozaki-kun",
    image: "https://cdn.myanimelist.net/images/anime/5/66083.webp",
    genres: ["Comedy", "Romance"],
  },
  {
    id: 35062,
    title: "Mahoutsukai no Yome",
    image: "https://cdn.myanimelist.net/images/anime/3/88476.webp",
    genres: ["Drama", "Fantasy", "Romance"],
  },
  {
    id: 21995,
    title: "Ao Haru Ride",
    image: "https://cdn.myanimelist.net/images/anime/8/64813.webp",
    genres: ["Romance"],
  },
  {
    id: 48561,
    title: "Jujutsu Kaisen 0 Movie",
    image: "https://cdn.myanimelist.net/images/anime/1121/119044.webp",
    genres: ["Action", "Fantasy"],
  },
  {
    id: 39617,
    title: "Yakusoku no Neverland 2nd Season",
    image: "https://cdn.myanimelist.net/images/anime/1815/110626.webp",
    genres: ["Fantasy", "Sci-Fi", "Suspense"],
  },
  {
    id: 20787,
    title: "Black Bullet",
    image: "https://cdn.myanimelist.net/images/anime/1292/94693.webp",
    genres: ["Action", "Mystery", "Sci-Fi"],
  },
  {
    id: 40221,
    title: "Kami no Tou",
    image: "https://cdn.myanimelist.net/images/anime/1702/106229.webp",
    genres: ["Action", "Adventure", "Drama", "Fantasy", "Mystery"],
  },
  {
    id: 849,
    title: "Suzumiya Haruhi no Yuuutsu",
    image: "https://cdn.myanimelist.net/images/anime/1470/137929.webp",
    genres: ["Award Winning", "Comedy", "Mystery", "Sci-Fi"],
  },
  {
    id: 43608,
    title: "Kaguya-sama wa Kokurasetai: Ultra Romantic",
    image: "https://cdn.myanimelist.net/images/anime/1160/122627.webp",
    genres: ["Comedy", "Romance"],
  },
  {
    id: 32615,
    title: "Youjo Senki",
    image: "https://cdn.myanimelist.net/images/anime/5/82890.webp",
    genres: ["Action", "Fantasy"],
  },
  {
    id: 15451,
    title: "High School DxD New",
    image: "https://cdn.myanimelist.net/images/anime/12/47729.webp",
    genres: ["Action", "Comedy", "Fantasy", "Romance", "Ecchi"],
  },
  {
    id: 41353,
    title: "The God of High School",
    image: "https://cdn.myanimelist.net/images/anime/1722/107269.webp",
    genres: ["Action", "Fantasy"],
  },
  {
    id: 2251,
    title: "Baccano!",
    image: "https://cdn.myanimelist.net/images/anime/3/14547.webp",
    genres: ["Action", "Mystery", "Supernatural"],
  },
  {
    id: 45576,
    title: "Mushoku Tensei: Isekai Ittara Honki Dasu Part 2",
    image: "https://cdn.myanimelist.net/images/anime/1028/117777.webp",
    genres: ["Adventure", "Drama", "Fantasy", "Ecchi"],
  },
  {
    id: 37675,
    title: "Overlord III",
    image: "https://cdn.myanimelist.net/images/anime/1511/93473.webp",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 50602,
    title: "Spy x Family Part 2",
    image: "https://cdn.myanimelist.net/images/anime/1111/127508.webp",
    genres: ["Action", "Comedy"],
  },
  {
    id: 10165,
    title: "Nichijou",
    image: "https://cdn.myanimelist.net/images/anime/3/75617.webp",
    genres: ["Comedy"],
  },
  {
    id: 32995,
    title: "Yuri!!! on Ice",
    image: "https://cdn.myanimelist.net/images/anime/6/81149.webp",
    genres: ["Award Winning", "Sports"],
  },
  {
    id: 51009,
    title: "Jujutsu Kaisen 2nd Season",
    image: "https://cdn.myanimelist.net/images/anime/1792/138022.webp",
    genres: ["Action", "Fantasy"],
  },
  {
    id: 42203,
    title: "Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season Part 2",
    image: "https://cdn.myanimelist.net/images/anime/1724/117421.webp",
    genres: ["Drama", "Fantasy", "Suspense"],
  },
  {
    id: 33487,
    title: "Masamune-kun no Revenge",
    image: "https://cdn.myanimelist.net/images/anime/12/83709.webp",
    genres: ["Comedy", "Romance"],
  },
  {
    id: 37799,
    title: "Tokyo Ghoul:re 2nd Season",
    image: "https://cdn.myanimelist.net/images/anime/1545/121995.webp",
    genres: ["Action", "Fantasy", "Horror", "Suspense"],
  },
  {
    id: 48926,
    title: "Komi-san wa, Comyushou desu.",
    image: "https://cdn.myanimelist.net/images/anime/1899/117237.webp",
    genres: ["Comedy"],
  },
  {
    id: 24439,
    title: "Kekkai Sensen",
    image: "https://cdn.myanimelist.net/images/anime/1449/142053.webp",
    genres: ["Action", "Fantasy"],
  },
];
